apiVersion: apps/v1
kind: Deployment
metadata:
  name: kokoro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kokoro
  template:
    metadata:
      labels:
        app: kokoro
    spec:
      containers:
      - name: kokoro
        image: unprofessional/kokoro:rc-0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3030  # Ensure this matches the container's port (Dockerfile)
        env:  # Environment variables go here (not under ports)
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: pg-host
              key: PG_HOST
        - name: PG_PORT
          valueFrom:
            secretKeyRef:
              name: pg-port
              key: PG_PORT
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: pg-user
              key: PG_USER
        - name: PG_PASS
          valueFrom:
            secretKeyRef:
              name: pg-pass
              key: PG_PASS
        - name: PG_DB_KOKORO
          valueFrom:
            secretKeyRef:
              name: pg-db-kokoro
              key: PG_DB_KOKORO
        - name: MODEL_PROVIDER
          valueFrom:
            secretKeyRef:
              name: model-provider
              key: MODEL_PROVIDER
        - name: OLLAMA_BASE_URL
          valueFrom:
            secretKeyRef:
              name: ollama-base-url
              key: OLLAMA_BASE_URL
        # TODO: OPENAI_URL (if needed)
        # TODO: OPENAI_API_KEY (if needed)
