openapi: 3.0.0
info:
  title: 'LangChain Pipeline Boilerplate'
  version: '1.0.0'
components:
  schemas:

    SuccessId:
      type: 'object'
      properties:
        id:
          type: 'number'
          description: 'Success ID'
      required:
        - 'id'
      additionalProperties: false

    SuccessIds:
      type: 'object'
      properties:
        successIds:
          type: 'array'
          description: 'An array of SuccessId objects'
          items:
            $ref: '#/components/schemas/SuccessId'
      required:
        - 'successIds'
      additionalProperties: false

    Error:
      type: 'object'
      properties:
        code:
          type: 'number'
          description: 'Error status code'
        message:
          type: 'string'
          description: 'Error message detail'
      required:
        - 'code'
        - 'message'
      additionalProperties: false

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: langchain-pipeline-app

servers:
  - url: 'http://localhost:3030'
    description: 'Make OpenAPI Docs aware of the hosted location'

paths:
  ## Pipeline ##
  /pipeline:
    get:
      summary: 'FIXME: Hello world for now'
      tags:
        - 'Pipeline'
      operationId: 'pipelineControllerFn'
      security:
        - basicAuth: []
      responses:
        200:
          description: 'FIXME: Hello world!'
        default:
          description: 'An error occurred'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
tags:
  - name: 'Pipeline'
    description: 'These endpoints deal with main pipeline'